# Generated by Django 5.0.3 on 2024-03-26 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_rename_locarb_addlocarb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='title',
            field=models.TextField(default='العنوان باللغة العربية'),
        ),
        migrations.AlterField(
            model_name='description',
            name='title_en',
            field=models.TextField(default='العنوان باللغه الانجليزية'),
        ),
    ]
