# Generated by Django 5.0.3 on 2024-03-26 03:16

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_description_title_alter_description_title_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='description',
            field=tinymce.models.HTMLField(default='النص باللغه العربية'),
        ),
        migrations.AlterField(
            model_name='description',
            name='description_en',
            field=tinymce.models.HTMLField(default='النص باللغه الانجليزية'),
        ),
        migrations.AlterField(
            model_name='description',
            name='title',
            field=tinymce.models.HTMLField(default='العنوان باللغة العربية'),
        ),
        migrations.AlterField(
            model_name='description',
            name='title_en',
            field=tinymce.models.HTMLField(default='العنوان باللغه الانجليزية'),
        ),
    ]
